- name: test connectivity
  hosts: web-server-1,web-server-2,db-server
  vars:
    ansible_ssh_private_key_file: /home/boris/.ssh/google_compute_engine
    ansible_user: boris.chepikov
  tasks:
  - ping:
      
