---
# tasks file for mysql
  - name: Install MySQL database
    apt:
      name: "{{ item }}"
    with_items:
     - default-mysql-server
     - default-mysql-client

  - name: Start Mysql Service
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Create Application Database
    mysql_db: name={{ db_name }} 

  - name: Create Application DB User
    mysql_user: name={{ db_user }} password={{ db_password }} priv='*.*:ALL' host='%' 
    
  - name: update MySQL conf file
    ini_file:
      path: /etc/mysql/my.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
      
  - name: Start Mysql Service
    service:
      name: mysql
      state: restarted
      enabled: yes
