    - name: Install Python Flask dependencies
      pip:
        name: '{{ item }}'
        state: present
      with_items:
       - flask
       - flask-mysql
    
    - name: install git
      apt:
        name: git
        state: latest

    - name: download web-server code
      git:
        repo: 'https://github.com/MrChepik/webapp.git'
        dest: /opt/simple-webapp
    
    - name: Print a command
      debug:
        msg: MYSQL_DATABASE_HOST={{ db_server_ip }} FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 --port=80 &

    - name: Start web-application
      shell: MYSQL_DATABASE_HOST={{ db_server_ip }} FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 --port=80 &
