---
# tasks file for server
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  
- name: install software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - default-mysql-server
    - php-mysql
    - php
    - libapache2-mod-php

    
