-
  name: inventory
  hosts: hosts
  strategy: free
  any_errors_fatal: true
  vars:
    db_name: my_db
    db_user: admin
    db_user_password: Passw0rd
  roles:
  - deploy_python
  - deploy_db
  - deploy_web

  tasks:
  - name: Rolling back - Ending playbook
    fail:
      msg: "Configuration file is not valid. Please check that before re-running the playbook."
    when: result is failed
  - mail:
      to: somebody@xxxmail.com
      subject: "Web server deployed"
      body: Web Server have been Deployed!!
    ignore_errors: yes
    
    
